#!/usr/bin/env sh

#
# Gradle start up script for POSIX generated by OFA.
#

# Resolve the directory of this script.
APP_HOME=$(cd "$(dirname "$0")" && pwd)

# Use the wrapper jar to launch Gradle.
exec java -jar "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" "$@"
